services:
  - type: web
    name: makemyway-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      # PORT supprimé - Render fournit automatiquement cette variable